services:
  mysql-todo:
    image: mysql:8.0
    container_name: mysql-todo
    environment:
      MYSQL_DATABASE: todo_db
      MYSQL_USER: davi
      MYSQL_PASSWORD: davi
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -proot || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  api:
    build:
      context: ./todo-api
      dockerfile: Dockerfile
    container_name: todo-api
    depends_on:
      mysql-todo:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./todo-api:/var/www
    working_dir: /var/www
    command: php-fpm

  frontend:
    build:
      context: ./todo-front
      dockerfile: Dockerfile
    container_name: todo-front
    restart: unless-stopped
    volumes:
      - ./todo-front:/usr/share/nginx/html:ro
    ports:
      - "8080:80"

  api-nginx:
    image: nginx:alpine
    container_name: todo-api-nginx
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "8000:80"
    volumes:
      - ./todo-api:/var/www
      - ./todo-api/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./todo-api/nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  mysql_data: