version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-todo
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: todo_db
      MYSQL_USER: davi
      MYSQL_PASSWORD: senha123
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql_data:/var/lib/mysql
